//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boutique.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Orders = new HashSet<Order>();
        }
        [Key, Column(Order = 1)]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required(ErrorMessage = "Vui l?ng nh?p H? Tên")]
        [StringLength(50, MinimumLength = 5, ErrorMessage = "Vui l?ng nh?p h? tên th?t")]
        public string FullName { get; set; }
        [Required(ErrorMessage = "Vui l?ng nh?p Email")]
        [RegularExpression(@"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}", ErrorMessage = "Vui l?ng nh?p email h?p l?")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Vui l?ng nh?p M?t kh?u")]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,15}$", ErrorMessage = "M?t kh?u t?i thi?u 8 kí t?, bao g?m ch? cái in hoa, s? và k? t? ð?c bi?t")]
        public string Password { get; set; }
        public string Avatar { get; set; }
        public string Address { get; set; }
        [Required(ErrorMessage = "Vui l?ng nh?p s? ði?n tho?i")]
        [RegularExpression(@"^(0[0-9]{9,10})$", ErrorMessage = "Vui l?ng nh?p s? ði?n tho?i h?p l?")]
        public string Phone { get; set; }
        public Nullable<bool> Member { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
