//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boutique.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        public Product()
        {
            this.Stocks = new HashSet<Stock>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Picture { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập tên sản phẩm")]
        public string Name { get; set; }
        public string Code { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập giá vốn")]
        public Nullable<double> costPrice { get; set; }
        public Nullable<double> unitPrice { get; set; }
        public Nullable<int> Sold { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập giảm giá")]
        [Range(0, 50, ErrorMessage = "Phạm vi 0-50%")]
        public Nullable<int> Sale { get; set; }
        public Nullable<System.DateTime> stockInDate { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Stock> Stocks { get; set; }
    }
}
