//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boutique.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Xunit.Sdk;

    public partial class Stock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stock()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập mã màu")]
        public Nullable<int> ColorId { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập kích thước")]
        public Nullable<int> SizeId { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập số lượng sản phẩm")]
        [Range(0, 10000, ErrorMessage = "Số lượng sản phẩm phải lớn hơn 0")]
        public Nullable<int> Stock1 { get; set; }
        public Nullable<System.DateTime> stockInDate { get; set; }
    
        public virtual Color Color { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual Product Product { get; set; }
        public virtual Size Size { get; set; }
    }
}
